# this file generated by script/generate pickle

Given(/^#{CaptureModel} exists$/) do |name|
  create_model(name)
end

Given(/^#{CaptureModel} exists with #{CaptureFields}$/) do |name, fields|
  create_model(name, fields)
end

Then(/^#{CaptureModel} should exist with #{CaptureFields}$/) do |name, fields|
  find_model(name, fields).should_not == nil
end

Then(/^#{CaptureModel} should be (?:an? )?([\w ]+)$/) do |name, predicate|
  model(name).should send("be_#{predicate.gsub(' ','_')}")
end

Then(/^#{CaptureModel} should not be (?:an? )?([\w ]+)$/) do |name, predicate|
  model(name).should_not send("be_#{predicate.gsub(' ','_')}")
end
