# this file generated by pickle
#
# Make sure that you are loading your factory of choice in your cucumber environment
#
# For machinist add: features/support/machinist.rb
#
#    require 'machinist/active_record' # or your chosen adaptor
#    require File.dirname(__FILE__) + '/../../spec/blueprints' # or wherever your blueprints are
#    Before { Sham.reset } # to reset Sham's seed between scenarios so each run has same random sequences
#
# For factory_girl add: features/support/factory_girl.rb
#    require 'factory_girl'
#    require File.dirname(__FILE__) + '/../../spec/factories' # or wherever your factories are

# Your ORM adapter(s) should be autoloaded, but if not, require it (them) here
# require 'pickle/orm_adapters/<YOUR ORM>

require 'pickle/cucumber'
<%- if pickle_path -%>
require 'pickle/path'
<%- end -%>
<%- if pickle_email -%>
require 'pickle/email'
<%- end -%>

Pickle.configure do |config|

  # tell pickle to allow the following factory names in #pickle_ref (in adition to any single \w+)
  #
  # config.factories = ['admin user', 'troublesome user']
  
  
  # tell pickle to allow the following predicates in #pickle_predicate (in addition to anything in double quotes)
  #
  # config.predicates = ['empty', 'full', 'unfeasibly large']


  # tell pickle to alias the following terms to factories
  #
  # config.alias 'external user', :to => 'external_plugin_user'

  
  # tell pickle to automatically make models with an attribute corresponding to a label in the pickle ref
  #
  # config.map_label_for 'user', :to => 'name'
  # config.map_label_for 'post', 'blog', 'site', :to => 'title'

  
  # tell pickle to map a whole expression to a pickle ref
  #
  # config.map 'I', 'me', 'myself', :to => 'user "me"'

  
  # tell pickle about a new adapter class, or turn off a built-in adapter (by leaving it out)
  #
  # config.adapters = [:machinist, MyGreatAdapter]
  
  
  # map a particular factory name (like 'user') to a particlar adapter instance
  # 
  # config.adapter_map['user'] = MySpecialCaseAdapter
  # config.adapter_map['file'] = MyFileAdapter.new('tmp/pickle-files')
end
